services:
  nginx:
    ports:
      - 80:80
    volumes:
      - ./project:/var/www/html
      - ./nginx/conf.d:/etc/nginx/conf.d

  php:
    volumes:
      - ./project:/var/www/html

  db:
    ports:
      - 3306:3306
