volumes:
  mysql-data:
    driver: local
  redis-data:
    driver: local

networks:
  default:
    driver: bridge

services:
  nginx:
    build:
      context: nginx
    volumes:
      - ./project:/var/www/html
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - default
    depends_on:
      - php

  db:
    image: 'mysql/mysql-server:8.0'
    expose:
      - '3306'
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - default

  php:
    build:
      context: ./project/vendor/laravel/sail/runtimes/8.2
      dockerfile: Dockerfile
      args:
        WWWGROUP: '${WWWGROUP}'
    expose:
      - 80
    ports:
      - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      WWWUSER: '${WWWUSER}'
      LARAVEL_SAIL: 1
      XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
      XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
      IGNITION_LOCAL_SITES_PATH: '${PWD}'
    networks:
      - default
    depends_on:
      - db
      - redis

  redis:
    image: 'redis:alpine'
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
      - redis-data:/data
    networks:
      - default
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      retries: 3
      timeout: 5s
