services:
  nginx:
    volumes:
      - ./project:/var/www/html
      - ./nginx/conf.d:/etc/nginx/conf.d

  db:
    ports:
      - 3306:3306
    volumes:
      - ./mysql/init.d/:/var/lib/mysql/init.d/

  php:
    build:
      context: ./project/vendor/laravel/sail/runtimes/8.2
      dockerfile: Dockerfile
      args:
        WWWGROUP: '${WWWGROUP}'
    volumes:
      - ./project:/var/www/html
